// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBudykbTwXD7K6Sf3v0cHTRhdFAN74rCcI',
    appId: '1:249626903805:web:577b9df2e6389750fbaa94',
    messagingSenderId: '249626903805',
    projectId: 'e-voting-app-32a56',
    authDomain: 'e-voting-app-32a56.firebaseapp.com',
    storageBucket: 'e-voting-app-32a56.firebasestorage.app',
    measurementId: 'G-9JR68SPQ7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHbyTZv61cerbHinDxBd5D1YSYS8T-7KI',
    appId: '1:249626903805:android:f8ea4df0db56bccffbaa94',
    messagingSenderId: '249626903805',
    projectId: 'e-voting-app-32a56',
    storageBucket: 'e-voting-app-32a56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB92VUSq_RzDS42T-36Q-SMtGwWOvAM61s',
    appId: '1:249626903805:ios:fe25fa8e47820405fbaa94',
    messagingSenderId: '249626903805',
    projectId: 'e-voting-app-32a56',
    storageBucket: 'e-voting-app-32a56.firebasestorage.app',
    iosBundleId: 'com.example.eVote',
  );
}
